package com.gradleup.auto.manifest

import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property

interface AutoManifestExtension {
    /**
     * packageName that will be set in generated AndroidManifest.xml
     *
     * Android Gradle Plugin will use this to generate BuildConfig and R classes under this package.
     */
    val packageName: Property<String>

    /**
     * Applies recursively to submodules (subprojects), so you don't have to configure every single module.
     * Submodule package names will be auto generated by using their relative path
     *
     * Default: true
     */
    val applyRecursively: Property<Boolean>

    /**
     * Using dashes `-` is pretty common in module names. But they are not allowed within Java package names.
     *
     * When this flag is enabled, they will be replaced by a dot. By default, they will be replaced with an underscore.
     * Default is set to `false` to prevent package name collusion in rare cases.
     *
     * Default: false
     */
    val replaceDashesWithDot: Property<Boolean>

    /**
     * Read-only generated AndroidManifest.xml location for advanced users.
     */
    val generatedManifest: RegularFileProperty
}
